### ISSUE TITLE
Dirty documents after running the Export Flat patterns macro

### ISSUE THREAD

**Issue by artem1t** [xarial/codestack#13]

**Comment by artem1t** [comment]
As reported this message blocks the execution so needs to be resolved

**Comment by ALANApplesauce** [comment]
Artem,

I wanted to follow up on this......

**Comment by artem1t** [comment]
Hi Alan,

I was not able to reproduce the issue. But there were quite a few revisions of the macro. Could you please try the latest version from the site? If the issue is still reproducible, would it be possible to have a remote session with you to troubleshoot? If so, please send me an e-mail to info@xarial.com and we will organize the session.

Thanks,
Artem

**Comment by ALANApplesauce** [comment]
Let me try and run the new version first. Do I just go to the original post and copy the code from there? Or where is the updated code located at?

**Comment by artem1t** [comment]
> Let me try and run the new version first. Do I just go to the original post and copy the code from there? Or where is the updated code located at? 

Yes, macro is at original post

**Comment by ALANApplesauce** [comment]
ok thanks!!

**Comment by ALANApplesauce** [comment]
Looks like the updated version works! Thanks for your help! I can't thank
you enough!

**Comment by artem1t** [comment]
Great, I will close the ticket. Could you please attach the original macro here if you still have it (the one which doesn't work). As I have about 5 revisions of this macro - I want to try to isolate which one is exactly caused the problem so will not use it in future.

**Comment by ALANApplesauce** [comment]
Attached is the macro.
