### ISSUE TITLE
Macro to export SOLIDWORKS file to multiple formats + PDF3D addin

### ISSUE THREAD

**Issue by JLozanoM** [xarial/codestack#175]
Hi!,

I am very grateful to the author/s of the "Macro to export SOLIDWORKS file to multiple formats", because is very useful in my daily work!😊👌

[https://www.codestack.net/solidworks-api/import-export/export-multi-formats/](url)

I would like to know, if there is a possibily, to add another format for exporting solids in PDF3D, in the same macro file.

Thank you very much!.

**Comment by artem1t** [comment]
Macro has been modified and 3D PDF is now supported by changing this constant

`Const PDF_3D As Boolean = True`
